import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Plus,Users,ReceiptText,WalletCards,CheckCircle2,Trash2,ChevronLeft}from'lucide-react';import'./style.css';
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n||0);
const seed={group:'Room 12',people:[{id:'me',name:'You'},{id:'daniel',name:'Daniel'},{id:'tobi',name:'Tobi'}],expenses:[]};
function App(){const[data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem('wow-data'))||seed}catch{return seed}});const[page,setPage]=useState('home');const[form,setForm]=useState({title:'',amount:'',payer:'me',members:['me','daniel','tobi']});useEffect(()=>localStorage.setItem('wow-data',JSON.stringify(data)),[data]);
const ledger=useMemo(()=>{let b={};data.people.forEach(p=>b[p.id]=0);data.expenses.forEach(e=>{const share=e.amount/e.members.length;b[e.payer]+=e.amount; e.members.forEach(id=>b[id]-=share)});return b},[data]);
const settlements=useMemo(()=>{let debt=data.people.map(p=>({id:p.id,name:p.name,v:ledger[p.id]}));let owe=debt.filter(x=>x.v<-.01).map(x=>({...x,v:-x.v})),get=debt.filter(x=>x.v>.01).map(x=>({...x})),out=[];for(const d of owe){for(const c of get){if(d.v<=.01)break;if(c.v<=.01)continue;let a=Math.min(d.v,c.v);out.push({from:d.name,to:c.name,amount:a});d.v-=a;c.v-=a}}return out},[ledger,data.people]);
function addExpense(e){e.preventDefault();let a=Number(form.amount);if(!form.title.trim()||!a||!form.members.length)return;setData(d=>({...d,expenses:[{id:Date.now(),title:form.title.trim(),amount:a,payer:form.payer,members:form.members,date:new Date().toISOString()},...d.expenses]}));setForm(f=>({...f,title:'',amount:''}));setPage('home')}
const remove=id=>setData(d=>({...d,expenses:d.expenses.filter(e=>e.id!==id)}));const toggle=id=>setForm(f=>({...f,members:f.members.includes(id)?f.members.filter(x=>x!==id):[...f.members,id]}));
return <div className="app"><header>{page!=='home'?<button className="icon" onClick={()=>setPage('home')}><ChevronLeft/></button>:<div className="mark">₦</div>}<div><small>EXPENSE SPLITTER</small><h1>{data.group}</h1></div></header>
{page==='home'&&<><section className="hero"><span>GROUP BALANCE</span><strong>{settlements.length?`${settlements.length} payment${settlements.length>1?'s':''} to settle`:'All settled up'}</strong><p>{data.people.length} people · {data.expenses.length} expenses</p></section><div className="grid"><button className="action primary" onClick={()=>setPage('add')}><Plus/><b>Add expense</b><span>Split a new bill</span></button><button className="action" onClick={()=>setPage('people')}><Users/><b>People</b><span>Manage group</span></button></div><h2>Who owes who?</h2><section className="card">{settlements.length?settlements.map((s,i)=><div className="settle" key={i}><div><b>{s.from}</b><span> owes </span><b>{s.to}</b></div><strong>{money(s.amount)}</strong></div>):<div className="empty"><CheckCircle2/><b>Nobody owes anything</b><span>Add an expense to get started.</span></div>}</section><div className="titleRow"><h2>Recent expenses</h2><ReceiptText/></div><section className="card">{data.expenses.length?data.expenses.map(e=><div className="expense" key={e.id}><div className="receipt">₦</div><div className="grow"><b>{e.title}</b><span>{data.people.find(p=>p.id===e.payer)?.name} paid · split {e.members.length} ways</span></div><strong>{money(e.amount)}</strong><button className="trash" onClick={()=>remove(e.id)}><Trash2/></button></div>):<div className="empty compact"><WalletCards/><b>No expenses yet</b></div>}</section></>}
{page==='add'&&<><h2>Add an expense</h2><form className="card form" onSubmit={addExpense}><label>WHAT WAS IT FOR?<input autoFocus placeholder="e.g. Rice & stew" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>AMOUNT (₦)<input type="number" min="1" placeholder="8500" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>WHO PAID?<select value={form.payer} onChange={e=>setForm({...form,payer:e.target.value})}>{data.people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>SPLIT BETWEEN</label><div className="chips">{data.people.map(p=><button type="button" className={form.members.includes(p.id)?'chip on':'chip'} onClick={()=>toggle(p.id)} key={p.id}>{p.name}</button>)}</div>{form.amount&&form.members.length>0&&<div className="preview">Each person's share <b>{money(Number(form.amount)/form.members.length)}</b></div>}<button className="submit">Split expense</button></form></>}
{page==='people'&&<People data={data} setData={setData}/>}<footer>WHO OWES WHO? · saved on this device</footer></div>}
function People({data,setData}){const[name,setName]=useState('');function add(e){e.preventDefault();if(!name.trim())return;let id=Date.now().toString();setData(d=>({...d,people:[...d.people,{id,name:name.trim()}]}));setName('')}return <><h2>People</h2><section className="card people">{data.people.map(p=><div className="person" key={p.id}><div className="avatar">{p.name[0].toUpperCase()}</div><b>{p.name}</b>{p.id==='me'&&<span>You</span>}</div>)}</section><form className="addPerson" onSubmit={add}><input placeholder="Friend's name" value={name} onChange={e=>setName(e.target.value)}/><button><Plus/> Add</button></form><p className="hint">For this experiment, people with existing expenses aren't deleted so old splits stay accurate.</p></>}
createRoot(document.getElementById('root')).render(<App/>);
